Repository gircore/gir.core, pull requests merged in 2020-11, with the labels that each got.

#99 Feature/support interfaces
  Generator/Gir/GClass.cs
  Generator/Gir/GImplement.cs
  Generator/Templates/GObject/class.sbntxt
  Generator/Templates/GObject/interface.sbntxt
  Libs/GObject/Classes/Object.Properties.cs
  Libs/GObject/Classes/Object.cs
  Libs/GObject/Structs/Value.cs
  Libs/Gtk3/Classes/Notebook.cs
  Libs/Gtk3/Classes/Window.cs
  Samples/Gtk3/QuickStart/Program.cs
Labels: Discussion

#107 Add VS Solution File
  GirCore.sln
Labels: Enhancement

#105 Type Dictionary Improvements
  Generator/GLibGenerator.cs
  Generator/Templates/Shared/global.sbntxt
  Libs/GLib/Classes/Filename.cs
  Libs/GObject/Classes/Object.TypeDictionary.cs
  Libs/GObject/Classes/Object.TypeIntegration.cs
  Libs/GObject/Classes/Object.cs
  Libs/GObject/Structs/Type.cs
  Libs/Gdk3/Classes/Screen.cs
  Libs/Gtk3/Classes/Box.cs
  Libs/Gtk3/Classes/Container.cs
  Libs/Gtk3/Classes/CssProvider.cs
  Libs/Gtk3/Classes/Dialog.cs
  Libs/Gtk3/Classes/Expander.cs
  Libs/Gtk3/Classes/Image.cs
  Libs/Gtk3/Classes/Label.cs
  Libs/Gtk3/Classes/ScrolledWindow.cs
  Libs/Gtk3/Classes/StyleContext.cs
  Libs/Gtk3/Classes/TextBuffer.cs
  Libs/Gtk3/Classes/TextView.cs
  Libs/Gtk3/Classes/Widget.cs
  Libs/Gtk3/Classes/Window.cs
  Libs/Gtk3/Interfaces/Orientable.cs
  Samples/Gtk3/GtkMinimal/DemoWindow.cs
  WINDOWS.md
Labels: Enhancement, bug
