Repository gircore/gir.core, pull requests merged in 2020-12, with the labels that each got.

#103 Widget Catalog Samples
  Generator/Templates/GObject/class.sbntxt
  Generator/Templates/GObject/interface.sbntxt
  Generator/Templates/GObject/signal.sbntxt
  Generator/Templates/Shared/field.sbntxt
  Generator/Templates/Shared/interface_property.sbntxt
  Generator/Templates/Shared/property.sbntxt
  Libs/GObject/Classes/Object.cs
  Libs/GObject/Classes/Property.cs
  Libs/GObject/Interfaces/IObject.cs
  Libs/Gio/Classes/PropertyAction.cs
  Libs/Gio/Classes/SimpleAction.cs
  Libs/Gtk3/Classes/AboutDialog.cs
  Libs/Gtk3/Classes/AccelGroup.cs
  Libs/Gtk3/Classes/AppChooserButton.cs
  Libs/Gtk3/Classes/AppChooserDialog.cs
  Libs/Gtk3/Classes/AppChooserWidget.cs
  Libs/Gtk3/Classes/Button.cs
  Libs/Gtk3/Classes/CellAreaBox.cs
  Libs/Gtk3/Classes/CellRendererProgress.cs
  Libs/Gtk3/Classes/CellView.cs
  Libs/Gtk3/Classes/ColorButton.cs
  Libs/Gtk3/Classes/ColorChooserDialog.cs
  Libs/Gtk3/Classes/ColorChooserWidget.cs
  Libs/Gtk3/Classes/ComboBox.cs
  Libs/Gtk3/Classes/Entry.cs
  Libs/Gtk3/Classes/FileChooserButton.cs
  Libs/Gtk3/Classes/FileChooserDialog.cs
  Libs/Gtk3/Classes/FileChooserNative.cs
  Libs/Gtk3/Classes/FileChooserWidget.cs
  Libs/Gtk3/Classes/FlowBox.cs
  Libs/Gtk3/Classes/FontButton.cs
  Libs/Gtk3/Classes/FontChooserDialog.cs
  Libs/Gtk3/Classes/FontChooserWidget.cs
  Libs/Gtk3/Classes/Grid.cs
  Libs/Gtk3/Classes/IconView.cs
  Libs/Gtk3/Classes/Layout.cs
  Libs/Gtk3/Classes/LevelBar.cs
  Libs/Gtk3/Classes/ListBoxRow.cs
  Libs/Gtk3/Classes/MenuItem.cs
  Libs/Gtk3/Classes/Paned.cs
  Libs/Gtk3/Classes/ProgressBar.cs
  Libs/Gtk3/Classes/Range.cs
  Libs/Gtk3/Classes/RecentAction.cs
  Libs/Gtk3/Classes/RecentChooserDialog.cs
  Libs/Gtk3/Classes/RecentChooserMenu.cs
  Libs/Gtk3/Classes/RecentChooserWidget.cs
  Libs/Gtk3/Classes/ScaleButton.cs
  Libs/Gtk3/Classes/Separator.cs
  Libs/Gtk3/Classes/SpinButton.cs
  Libs/Gtk3/Classes/Switch.cs
  Libs/Gtk3/Classes/TextView.cs
  Libs/Gtk3/Classes/ToolButton.cs
  Libs/Gtk3/Classes/ToolItem.cs
  Libs/Gtk3/Classes/ToolPalette.cs
  Libs/Gtk3/Classes/Toolbar.cs
  Libs/Gtk3/Classes/TreeView.cs
  Libs/Gtk3/Classes/Viewport.cs
  Libs/Gtk3/Classes/Window.cs
  Libs/Gtk3/Gtk3.csproj
  Libs/Gtk3/Interfaces/Orientable.cs
Labels: Enhancement, documentation

#138 Readme: Promote discussions and good first issues
  README.md
Labels: documentation

#133 Feature/compositetemplates
  Build/Projects.cs
  Generator/Resolver/TypeResolver.cs
  Libs/GLib/Classes/Bytes.cs
  Libs/GLib/Interfaces/IHandle.cs
  Libs/GObject/Classes/Object.TypeDictionary.cs
  Libs/GObject/Classes/Object.TypeHelper.cs
  Libs/GObject/Classes/Object.TypeIntegration.cs
  Libs/GObject/Classes/Object.cs
  Libs/GObject/Extensions/AssemblyExtension.cs
  Libs/GObject/Structs/Type.cs
  Libs/Gtk3/Classes/AboutDialog.cs
  Libs/Gtk3/Classes/AccelGroup.cs
  Libs/Gtk3/Classes/Box.cs
  Libs/Gtk3/Classes/Container.cs
  Libs/Gtk3/Classes/CssProvider.cs
  Libs/Gtk3/Classes/Notebook.cs
  Libs/Gtk3/Classes/StyleContext.cs
  Libs/Gtk3/Classes/Widget.CompositeWidget.cs
  Libs/Gtk3/Classes/Window.cs
  Libs/Gtk4/Core/Classes/Box.cs
  Libs/Gtk4/Core/Classes/Window.cs
  Libs/Handy/Core/Classes/Paginator.cs
  Libs/JavascriptCore/Core/Classes/Context.cs
  Libs/WebKitGTK/Core/Classes/WebView.cs
  Samples/Gtk3/QuickStart/Program.cs
  Samples/Gtk3/Template/CompositeWidget.cs
  Samples/Gtk3/Template/CompositeWidget.ui
  Samples/Gtk3/Template/Program.cs
  Samples/Gtk3/Template/Template.csproj
Labels: Enhancement

#154 Feature/build os independent dlls
  Generator/GLibGenerator.cs
  Generator/GObjectGenerator.cs
  Generator/Generator.cs
  Generator/Gir/GNamespace.cs
  Generator/Resolver/DllImportResolver.cs
  Generator/Templates/Shared/helper_dll_import.sbntxt
  Generator/Templates/Shared/module_dll_import.sbntxt
  Libs/Cairo/Classes/Module.cs
  Libs/GLib/Classes/Module.cs
  Libs/GObject/Classes/Module.cs
  Libs/Gdk3/Classes/Module.cs
  Libs/GdkPixbuf/Classes/Module.cs
  Libs/Gio/Classes/Module.cs
  Libs/Gst.Audio/Classes/Module.cs
  Libs/Gst.Base/Classes/Module.cs
  Libs/Gst.Pbutils/Classes/Module.cs
  Libs/Gst.Video/Classes/Module.cs
  Libs/Gst/Classes/Module.cs
  Libs/Gtk3/Classes/Module.cs
  Libs/Pango/Classes/Module.cs
Labels: Enhancement
